services:
  docs:
    image: kubernetes_test_v2_local_docs
    container_name: kubernetes_test_v2_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./kubernetes_test_v2:/app/kubernetes_test_v2:z
    ports:
      - '9000:9000'
    command: /start-docs
