apiVersion: v1
data:
  POSTGRES_DB: kubernetes_test_v2
  POSTGRES_HOST: postgres
  POSTGRES_PASSWORD: NIMxhmnzIewGBP0nuKbKQ69ik6xjJVxv9eAbpGofGef5eUeo6d4SfJ93x5VInT42
  POSTGRES_PORT: "5432"
  POSTGRES_USER: VNTdiUBJsFTUImttcEzAMFfjiTqpVHJw
  DATABASE_URL: postgres://VNTdiUBJsFTUImttcEzAMFfjiTqpVHJw:NIMxhmnzIewGBP0nuKbKQ69ik6xjJVxv9eAbpGofGef5eUeo6d4SfJ93x5VInT42@postgres:5432/kubernetes_test_v2
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: celerybeat-envs--production--postgres
  name: envs--production--postgres
