apiVersion: v1
data:
  CELERY_FLOWER_PASSWORD: CMhMwczeFns1VDZD3PU0tn1oJrLZ4xweTOc0a5ara7pzvQOt9IvIj6w9V3M88G1q
  CELERY_FLOWER_USER: PIUFZvGDMQqWeMFXKOCuNWAWbSInajof
  DJANGO_ACCOUNT_ALLOW_REGISTRATION: "False"
  DJANGO_ADMIN_URL: QuVP2loe1AIGxjUkQw8XY9nGiigYXeff/
  DJANGO_ALLOWED_HOSTS: .streamlined-analytics-testing.xyz
  DJANGO_SECRET_KEY: GGe5nDbn1KgkH5tGcsjBECJi8XasgQDzKqQm5ILxPHfwnbtp6xSXCNMM4jdAVuwk
  DJANGO_SECURE_SSL_REDIRECT: "False"
  DJANGO_SERVER_EMAIL: ""
  DJANGO_SETTINGS_MODULE: config.settings.production
  MAILGUN_API_KEY: ""
  MAILGUN_DOMAIN: ""
  REDIS_URL: redis://redis:6379/0
  SENTRY_DSN: ""
  WEB_CONCURRENCY: "4"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: celerybeat-envs--production--django
  name: envs--production--django
